export const products = [
  {
    id: 1,
    title: "Nikon D7100",
    price: 35000,
    stock: 2,
    description:
      "Body 7100, Ideal para los comienzos en los caminos profesionales",
    category: "Camaras RX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1687903831/NikonD7100_iiny5w.jpg",
  },
  {
    id: 2,
    title: "Nikon D3",
    price: 75000,
    stock: 4,
    description: "Body de Camara Full Frame Pro",
    category: "Camaras FX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1687903830/Nikon_D3_inbwdx.jpg",
  },
  {
    id: 3,
    title: "Nikon D610",
    price: 95000,
    stock: 5,
    description: "Body de Camara Full Frame Pro",
    category: "Camaras FX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1688818593/Nikon_D610_dl2gqx.jpg",
  },
  {
    id: 4,
    title: "Nikon D7500",
    price: 85000,
    stock: 2,
    description: "Body de Camara Semi Pro",
    category: "Camaras RX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1688818593/Nikon_D7500_ujc8gh.jpg",
  },
  {
    id: 5,
    title: "Nikon D5500",
    price: 42000,
    stock: 3,
    description: "Body de Camara Semi Pro",
    category: "Camaras RX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1688818593/Nikon_D5500_lsit4k.jpg",
  },
  {
    id: 6,
    title: "Nikon D850",
    price: 42000,
    stock: 1,
    description: "Body de camara FX , La mayor puesta en escena de las FX",
    category: "Camaras FX",
    img: "https://res.cloudinary.com/dgbffafla/image/upload/v1688818593/Nikon_D850_tprg9j.jpg",
  },
];
